version: '3.8'

services:
  neo4j:
    image: neo4j:5.15.0
    environment:
      - NEO4J_AUTH=neo4j/Oakmont2025!!
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app-network

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lp_discovery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data:
  postgres_data:

networks:
  app-network:
    driver: bridge 